### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by akivanc88** [usnistgov/dioptra#570] opened 2024-07-28 01:56 UTC
**Describe the bug**
2 links on the https://pages.nist.gov/dioptra/index.html do not work

**To Reproduce**
1. Go to https://pages.nist.gov/dioptra/index.html
2. Click on [Downloading Datasets](https://pages.nist.gov/dioptra/getting-started/acquiring-datasets.html) OR [Testbed REST API Reference](https://pages.nist.gov/dioptra/reference/api-reference-restapi.html)
3. Page times out

**Expected behavior**
It should point you to the child pages

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version : 22

**Comment by hbooth** [comment] 2024-07-29 12:18
Just tried to access the two indicated links and they both are working for me at the moment. Please try it again and let us know. It is possible that there was an interruption with the service which provides the pages external to this project.

**Comment by hbooth** [comment] 2024-08-01 17:09
Closing, as the issue is not occurring presently and is an issue in infrastructure and not for this project in particular.

**Closed by hbooth** 2024-08-01 17:09 UTC
Labels: bug
